-- ============================================================================
-- MediKiosk — Canonical Database Schema
-- ============================================================================
-- THIS FILE IS THE CONTRACT. All 6 branches depend on these exact names.
--
-- RULES FOR THE TEAM:
--   1. Do NOT edit this file on your feature branch. Ever.
--   2. Need a column/table? Add a NEW file: supabase/migrations/NN_your_name.sql
--      That way two devs adding columns never conflict on the same lines.
--   3. Table/column names here are FINAL. If you think one is wrong, say so in
--      the group chat before you write code against a different name.
--
-- HOW TO APPLY: paste this whole file into Supabase Dashboard > SQL Editor > Run.
-- Then apply rls.sql, then seed.sql.
-- ============================================================================

create extension if not exists "pgcrypto";

-- ============================================================================
-- ENUMS  (wrapped in DO blocks so re-running this file is safe)
-- ============================================================================

do $$ begin
  -- Staff roles. Patients are NOT auth users — they're rows in `patients`.
  create type user_role as enum ('doctor', 'triage', 'admin');
exception when duplicate_object then null; end $$;

do $$ begin
  -- Which OPD flow the session follows. Drives allopathic vs Dashavidha questions.
  create type opd_type as enum ('allopathic', 'ayush');
exception when duplicate_object then null; end $$;

do $$ begin
  -- Supported kiosk languages. Values are BCP-47 primary subtags so they map
  -- directly to Web Speech API locales (hi -> hi-IN) and Bhashini codes.
  create type language_code as enum
    ('en','hi','bn','ta','te','mr','gu','kn','ml','pa','or','as','ur');
exception when duplicate_object then null; end $$;

do $$ begin
  -- Intake session lifecycle. Dev 2 owns transitions; Dev 6 reads for the queue.
  create type session_state as enum (
    'created',              -- row exists, patient at welcome screen
    'language_selected',
    'consent_granted',
    'identified',           -- patient linked (ABHA / new / anonymous walk-in)
    'history_in_progress',
    'documents_in_progress',
    'generating_summary',
    'ready_for_doctor',     -- <- the state the doctor queue filters on
    'in_consultation',
    'completed',
    'abandoned',            -- patient walked away
    'expired'               -- inactivity timeout reaped it
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type input_mode as enum ('voice', 'touch', 'mixed');
exception when duplicate_object then null; end $$;

do $$ begin
  create type consent_status as enum ('granted', 'denied', 'revoked');
exception when duplicate_object then null; end $$;

do $$ begin
  create type document_type as enum
    ('prescription', 'lab_report', 'discharge_summary', 'imaging', 'other');
exception when duplicate_object then null; end $$;

do $$ begin
  create type document_status as enum
    ('uploaded', 'processing', 'completed', 'failed');
exception when duplicate_object then null; end $$;

do $$ begin
  create type entity_type as enum
    ('diagnosis','medication','allergy','investigation','procedure','symptom','vital');
exception when duplicate_object then null; end $$;

do $$ begin
  -- Provenance: did this come from the patient talking, or from a scanned page?
  create type entity_source as enum ('conversation', 'document', 'doctor');
exception when duplicate_object then null; end $$;

do $$ begin
  create type abnormal_flag as enum
    ('critical_low','low','normal','high','critical_high','unknown');
exception when duplicate_object then null; end $$;

do $$ begin
  -- Triage outcome. `emergency` must bypass the queue entirely.
  create type risk_level as enum ('routine', 'urgent', 'emergency');
exception when duplicate_object then null; end $$;

do $$ begin
  create type alert_status as enum ('open','acknowledged','resolved','dismissed');
exception when duplicate_object then null; end $$;

do $$ begin
  create type review_status as enum ('pending','accepted','amended','rejected');
exception when duplicate_object then null; end $$;

do $$ begin
  -- Standard clinical history sections. Order here = render order for the doctor.
  create type history_section as enum (
    'chief_complaint',
    'hpi',
    'past_medical',
    'past_surgical',
    'medications',
    'allergies',
    'family',
    'personal',
    'review_of_systems',
    'ayush'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type submission_status as enum ('pending','success','failed','retrying');
exception when duplicate_object then null; end $$;

-- ============================================================================
-- SHARED TRIGGER: keep updated_at honest
-- ============================================================================

create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- ============================================================================
-- 1. STAFF & INFRASTRUCTURE               [owner: Dev 1 — tasks 01,02,03,34]
-- ============================================================================

-- Staff accounts. 1:1 with Supabase auth.users. Patients never get auth rows.
create table if not exists profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  role         user_role not null default 'doctor',
  full_name    text not null,
  department   text,
  -- Doctors only see sessions routed to their department when this is set.
  registration_no text,
  phone        text,
  is_active    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- Physical kiosk registry. Lets admin disable a broken unit.
create table if not exists kiosks (
  id           uuid primary key default gen_random_uuid(),
  code         text unique not null,          -- e.g. 'KIOSK-OPD-01'
  location     text,
  opd_type     opd_type not null default 'allopathic',
  department   text,
  is_active    boolean not null default true,
  last_seen_at timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- ============================================================================
-- 2. PATIENTS & SESSIONS                  [owner: Dev 2 — tasks 04,05,06,07]
-- ============================================================================

create table if not exists patients (
  id            uuid primary key default gen_random_uuid(),
  -- 14-digit ABHA number. NULL for walk-in/anonymous patients.
  abha_number   text unique,
  abha_address  text,                          -- e.g. 'ayush@abdm'
  full_name     text not null,
  date_of_birth date,
  -- Kept separately because many patients only know their age, not their DOB.
  age_years     integer check (age_years between 0 and 130),
  gender        text check (gender in ('male','female','other','undisclosed')),
  phone         text,
  address_line  text,
  district      text,
  state         text,
  pincode       text,
  preferred_language language_code not null default 'hi',
  -- TRUE when the patient declined identification and we captured no PII.
  is_anonymous  boolean not null default false,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists patients_abha_idx  on patients (abha_number);
create index if not exists patients_phone_idx on patients (phone);

-- One row per patient visit to a kiosk. THE central table — most things FK here.
create table if not exists intake_sessions (
  id            uuid primary key default gen_random_uuid(),
  -- Nullable: session is created before the patient identifies themselves.
  patient_id    uuid references patients(id) on delete set null,
  kiosk_id      uuid references kiosks(id) on delete set null,
  -- Human-readable OPD queue token shown to the patient, e.g. 'A-042'.
  token_number  text not null,
  opd_type      opd_type not null default 'allopathic',
  department    text,
  state         session_state not null default 'created',
  language      language_code not null default 'hi',
  input_mode    input_mode not null default 'mixed',
  -- Denormalised from triage_alerts so the doctor queue can sort without a join.
  risk_level    risk_level not null default 'routine',
  -- Bumped on every patient interaction; the reaper expires stale sessions.
  last_activity_at timestamptz not null default now(),
  started_at    timestamptz not null default now(),
  completed_at  timestamptz,
  -- Set when a doctor opens the chart, so two doctors don't both claim a patient.
  claimed_by    uuid references profiles(id) on delete set null,
  claimed_at    timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists sessions_state_idx    on intake_sessions (state);
create index if not exists sessions_token_idx    on intake_sessions (token_number);
create index if not exists sessions_patient_idx  on intake_sessions (patient_id);
-- Composite index that backs the doctor queue query (emergency first, then FIFO).
create index if not exists sessions_queue_idx
  on intake_sessions (state, risk_level, started_at);

-- ============================================================================
-- 3. CONSENT                              [owner: Dev 2 — task 07]
-- ============================================================================

-- Append-only. A revocation is a NEW row with status='revoked', never an UPDATE.
-- This is what makes the DPDP Act audit trail defensible.
create table if not exists consents (
  id             uuid primary key default gen_random_uuid(),
  session_id     uuid not null references intake_sessions(id) on delete cascade,
  patient_id     uuid references patients(id) on delete set null,
  -- Bump when consent wording changes, so you can prove WHAT was agreed to.
  consent_version text not null default 'v1.0',
  status         consent_status not null,
  language       language_code not null,
  -- Granular scopes: {"history":true,"documents":true,"abdm_share":false}
  scopes         jsonb not null default '{}'::jsonb,
  -- TRUE if the patient played the audio explanation (low-literacy pathway).
  audio_played   boolean not null default false,
  ip_address     text,
  created_at     timestamptz not null default now()
);
create index if not exists consents_session_idx on consents (session_id);

-- ============================================================================
-- 4. CLINICAL HISTORY                     [owner: Dev 2 (08,09) + Dev 3 (13,14,15)]
-- ============================================================================

-- Raw per-question answers. Dev 2 writes touch answers, Dev 3 writes voice answers.
-- Both go here so the summary generator has one place to read from.
create table if not exists history_responses (
  id            uuid primary key default gen_random_uuid(),
  session_id    uuid not null references intake_sessions(id) on delete cascade,
  section       history_section not null,
  -- Stable key from the question bank, e.g. 'cc.primary', 'hpi.onset'.
  question_key  text not null,
  question_text text not null,
  -- Normalised answer. Always an object so the shape never surprises a reader:
  --   {"value": <any>, "label": "...", "unit": "..."}
  answer        jsonb not null default '{}'::jsonb,
  -- Verbatim patient speech, kept for the doctor to audit the AI's reading.
  raw_transcript text,
  input_mode    input_mode not null default 'touch',
  language      language_code,
  -- ASR/LLM confidence 0..1. NULL for touch input (touch is certain).
  confidence    numeric(4,3) check (confidence between 0 and 1),
  -- Order the question was actually asked in, for replaying the interview.
  sequence_no   integer,
  created_at    timestamptz not null default now()
);
create index if not exists history_responses_session_idx
  on history_responses (session_id, sequence_no);
-- One answer per question per session; re-answering UPSERTs.
create unique index if not exists history_responses_unique
  on history_responses (session_id, question_key);

-- The assembled, structured history. One row per session.
-- Each section is JSONB validated against the Zod schemas in src/lib/types.
create table if not exists clinical_history (
  session_id     uuid primary key references intake_sessions(id) on delete cascade,
  chief_complaint    jsonb not null default '{}'::jsonb,
  hpi                jsonb not null default '{}'::jsonb,
  past_medical       jsonb not null default '[]'::jsonb,
  past_surgical      jsonb not null default '[]'::jsonb,
  medications        jsonb not null default '[]'::jsonb,
  allergies          jsonb not null default '[]'::jsonb,
  family_history     jsonb not null default '[]'::jsonb,
  personal_history   jsonb not null default '{}'::jsonb,
  review_of_systems  jsonb not null default '{}'::jsonb,
  is_complete    boolean not null default false,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- AYUSH Dashavidha Pariksha.               [owner: Dev 6 — task 31]
-- Separate table (not a JSONB blob on clinical_history) so Dev 6 can build this
-- in parallel without ever touching Dev 2's table.
create table if not exists ayush_assessment (
  session_id    uuid primary key references intake_sessions(id) on delete cascade,
  -- Dashavidha Pariksha — the ten-fold examination.
  prakriti      jsonb not null default '{}'::jsonb,  -- {vata,pitta,kapha} scores
  vikriti       jsonb not null default '{}'::jsonb,  -- current dosha imbalance
  sara          text,                                 -- tissue essence
  samhanana     text,                                 -- body compactness
  pramana       jsonb not null default '{}'::jsonb,  -- anthropometry
  satmya        text,                                 -- habituation/tolerance
  sattva        text,                                 -- mental strength
  ahara_shakti  text,                                 -- digestive/food capacity
  vyayama_shakti text,                                -- exercise tolerance
  vaya          text,                                 -- age/life stage
  -- Supporting Ayurvedic assessment beyond the ten-fold exam.
  agni          text,                                 -- digestive fire
  koshtha       text,                                 -- bowel nature
  ahara_vihara  jsonb not null default '{}'::jsonb,  -- diet & lifestyle
  nidana        jsonb not null default '[]'::jsonb,  -- causative factors
  samprapti     jsonb not null default '{}'::jsonb,  -- pathogenesis
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- ============================================================================
-- 5. DOCUMENTS & MEDICAL INTELLIGENCE     [owner: Dev 5 — tasks 18-25]
-- ============================================================================

create table if not exists documents (
  id             uuid primary key default gen_random_uuid(),
  session_id     uuid not null references intake_sessions(id) on delete cascade,
  patient_id     uuid references patients(id) on delete set null,
  doc_type       document_type not null default 'other',
  status         document_status not null default 'uploaded',
  -- Path inside the private `medical-documents` Storage bucket. NEVER a public URL.
  storage_path   text not null,
  original_filename text,
  mime_type      text,
  file_size_bytes integer,
  page_count     integer default 1,
  -- Full OCR text, kept so the doctor can Ctrl-F the original.
  ocr_text       text,
  ocr_confidence numeric(4,3) check (ocr_confidence between 0 and 1),
  ocr_provider   text,                        -- 'gemini' | 'google-vision' | ...
  -- The clinical date ON the document (not upload time) — drives the timeline.
  document_date  date,
  issuing_facility text,
  error_message  text,
  uploaded_at    timestamptz not null default now(),
  processed_at   timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index if not exists documents_session_idx on documents (session_id);

-- Every clinical fact the AI extracted, from ANY source, with full traceability.
-- This table is what makes "click the med, see the original prescription" work.
create table if not exists extracted_entities (
  id            uuid primary key default gen_random_uuid(),
  session_id    uuid not null references intake_sessions(id) on delete cascade,
  -- NULL when source='conversation'. Set when source='document'.
  document_id   uuid references documents(id) on delete cascade,
  entity_type   entity_type not null,
  source        entity_source not null,
  -- Text exactly as it appeared, e.g. 'T. Metformin 500mg BD'.
  raw_text      text not null,
  -- Cleaned canonical name, e.g. 'Metformin'.  [task 22 normalisation]
  normalized_name text,
  -- Type-specific payload. Shapes are defined ONCE in src/lib/types/entities.ts:
  --   medication:    {dose, unit, frequency, route, duration}
  --   diagnosis:     {icd10?, status: 'active'|'resolved'}
  --   investigation: {value, unit, ref_low, ref_high}
  attributes    jsonb not null default '{}'::jsonb,
  confidence    numeric(4,3) check (confidence between 0 and 1),
  -- TRACEABILITY [task 25]: where on the page did this come from?
  page_number   integer,
  bounding_box  jsonb,                        -- {x,y,width,height} normalised 0..1
  -- Doctor verification state, so the UI can show "unverified AI extraction".
  is_verified   boolean not null default false,
  verified_by   uuid references profiles(id) on delete set null,
  created_at    timestamptz not null default now()
);
create index if not exists entities_session_idx on extracted_entities (session_id, entity_type);
create index if not exists entities_document_idx on extracted_entities (document_id);

-- Lab values, split out from extracted_entities because they need numeric
-- comparison against reference ranges.        [task 23 abnormal detection]
create table if not exists investigations (
  id            uuid primary key default gen_random_uuid(),
  session_id    uuid not null references intake_sessions(id) on delete cascade,
  document_id   uuid references documents(id) on delete cascade,
  entity_id     uuid references extracted_entities(id) on delete cascade,
  test_name     text not null,                -- as printed
  normalized_test_name text,                  -- canonical, e.g. 'Haemoglobin'
  loinc_code    text,
  -- Numeric when parseable; value_text holds things like 'Positive' / 'Trace'.
  value_numeric numeric,
  value_text    text,
  unit          text,
  ref_low       numeric,
  ref_high      numeric,
  ref_text      text,                         -- e.g. '<200' for cholesterol
  flag          abnormal_flag not null default 'unknown',
  test_date     date,
  created_at    timestamptz not null default now()
);
create index if not exists investigations_session_idx on investigations (session_id);
-- Partial index: the doctor view queries ONLY abnormal results first.
create index if not exists investigations_abnormal_idx
  on investigations (session_id) where flag <> 'normal';

-- Unified chronological medical timeline.     [task 24]
create table if not exists timeline_events (
  id            uuid primary key default gen_random_uuid(),
  session_id    uuid not null references intake_sessions(id) on delete cascade,
  document_id   uuid references documents(id) on delete set null,
  entity_id     uuid references extracted_entities(id) on delete set null,
  event_date    date,
  -- TRUE when the date was inferred ('last month') rather than printed.
  is_date_approximate boolean not null default false,
  event_type    entity_type not null,
  title         text not null,
  description   text,
  source        entity_source not null,
  created_at    timestamptz not null default now()
);
create index if not exists timeline_session_date_idx
  on timeline_events (session_id, event_date desc nulls last);

-- ============================================================================
-- 6. TRIAGE                               [owner: Dev 4 — tasks 16,17]
-- ============================================================================

create table if not exists triage_alerts (
  id            uuid primary key default gen_random_uuid(),
  session_id    uuid not null references intake_sessions(id) on delete cascade,
  risk_level    risk_level not null,
  status        alert_status not null default 'open',
  -- Stable id from the rules engine, e.g. 'RF_CHEST_PAIN_DYSPNOEA'.
  rule_id       text not null,
  rule_name     text not null,
  -- Plain-English reason shown to triage staff. No jargon, no AI hedging.
  reason        text not null,
  -- The specific answers that fired the rule, for staff to sanity-check.
  triggering_findings jsonb not null default '[]'::jsonb,
  -- 'rules' = deterministic engine (trustworthy), 'llm' = model suggestion.
  detected_by   text not null default 'rules',
  acknowledged_by uuid references profiles(id) on delete set null,
  acknowledged_at timestamptz,
  resolved_by   uuid references profiles(id) on delete set null,
  resolved_at   timestamptz,
  resolution_note text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists alerts_open_idx
  on triage_alerts (status, risk_level, created_at desc);
create index if not exists alerts_session_idx on triage_alerts (session_id);

-- ============================================================================
-- 7. SUMMARY & DOCTOR REVIEW              [owner: Dev 4 (26,27) + Dev 6 (28,29,30)]
-- ============================================================================

-- Versioned. The AI draft is version 1 and is NEVER overwritten — a doctor's
-- edit inserts a new version. This is the "editable, never autonomous" guarantee.
create table if not exists summaries (
  id            uuid primary key default gen_random_uuid(),
  session_id    uuid not null references intake_sessions(id) on delete cascade,
  version       integer not null default 1,
  -- Structured summary validated against ClinicalSummarySchema (Zod).
  content       jsonb not null default '{}'::jsonb,
  -- Rendered markdown for fast display, derived from `content`.
  rendered_text text,
  review_status review_status not null default 'pending',
  -- Provenance & cost tracking [task 34].
  model_name    text,
  prompt_tokens integer,
  completion_tokens integer,
  generation_ms integer,
  -- Guardrail results [task 27]: {"schema_valid":true,"unsupported_claims":[...]}
  validation    jsonb not null default '{}'::jsonb,
  -- NULL on the AI draft; set on doctor-authored versions.
  created_by    uuid references profiles(id) on delete set null,
  created_at    timestamptz not null default now()
);
create unique index if not exists summaries_version_unique
  on summaries (session_id, version);

-- Field-level audit of what the doctor changed. Powers "AI accuracy" metrics
-- and is the strongest evidence for judges that the human stays in the loop.
create table if not exists summary_reviews (
  id            uuid primary key default gen_random_uuid(),
  summary_id    uuid not null references summaries(id) on delete cascade,
  session_id    uuid not null references intake_sessions(id) on delete cascade,
  doctor_id     uuid not null references profiles(id) on delete cascade,
  action        review_status not null,
  -- JSON Pointer to the changed field, e.g. '/hpi/onset'.
  field_path    text,
  ai_value      jsonb,
  doctor_value  jsonb,
  note          text,
  created_at    timestamptz not null default now()
);
create index if not exists reviews_session_idx on summary_reviews (session_id);

-- ============================================================================
-- 8. INTEGRATION, AUDIT, OBSERVABILITY    [owner: Dev 6 (33) + Dev 1 (34)]
-- ============================================================================

-- Every ABDM/HIS push attempt, with the exact FHIR payload sent.
-- Showing this table in the demo is what makes the integration story credible.
create table if not exists fhir_submissions (
  id            uuid primary key default gen_random_uuid(),
  session_id    uuid not null references intake_sessions(id) on delete cascade,
  -- 'abdm-phr' | 'his-emr'
  target        text not null,
  resource_type text not null default 'Bundle',
  status        submission_status not null default 'pending',
  -- The literal FHIR Bundle we sent. Judges WILL ask to see this.
  payload       jsonb not null,
  response_body jsonb,
  http_status   integer,
  attempt_count integer not null default 0,
  last_error    text,
  submitted_at  timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists fhir_session_idx on fhir_submissions (session_id);

-- Append-only audit log. Required for DPDP Act defensibility.
create table if not exists audit_logs (
  id            uuid primary key default gen_random_uuid(),
  -- Staff actor. NULL for patient/kiosk-originated actions.
  actor_id      uuid references profiles(id) on delete set null,
  actor_role    text,
  -- Verb, e.g. 'session.created', 'document.viewed', 'summary.amended'.
  action        text not null,
  resource_type text,
  resource_id   uuid,
  session_id    uuid references intake_sessions(id) on delete set null,
  metadata      jsonb not null default '{}'::jsonb,
  ip_address    text,
  user_agent    text,
  created_at    timestamptz not null default now()
);
create index if not exists audit_created_idx  on audit_logs (created_at desc);
create index if not exists audit_session_idx  on audit_logs (session_id);

-- ============================================================================
-- TRIGGERS
-- ============================================================================

do $$
declare t text;
begin
  foreach t in array array[
    'profiles','kiosks','patients','intake_sessions','clinical_history',
    'ayush_assessment','documents','triage_alerts','fhir_submissions'
  ] loop
    execute format(
      'drop trigger if exists set_updated_at_%1$s on %1$s;
       create trigger set_updated_at_%1$s before update on %1$s
         for each row execute function set_updated_at();', t);
  end loop;
end $$;

-- Auto-create a profile row when a staff member signs up.
create or replace function handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.email),
    coalesce((new.raw_user_meta_data->>'role')::user_role, 'doctor')
  )
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- Keep intake_sessions.risk_level in sync with the worst open alert, so the
-- doctor queue never needs a join. Dev 4 fires alerts; Dev 6 just reads the column.
create or replace function sync_session_risk()
returns trigger language plpgsql as $$
begin
  update intake_sessions s
     set risk_level = greatest_risk.lvl
    from (
      select coalesce(max(risk_level::text)::risk_level, 'routine') as lvl
        from triage_alerts
       where session_id = new.session_id
         and status in ('open','acknowledged')
    ) as greatest_risk
   where s.id = new.session_id;
  return new;
end $$;

drop trigger if exists on_triage_alert_change on triage_alerts;
create trigger on_triage_alert_change
  after insert or update of status, risk_level on triage_alerts
  for each row execute function sync_session_risk();

-- ============================================================================
-- REALTIME  [task 17] — enables Supabase Realtime subscriptions for Dev 4/Dev 6
-- ============================================================================

do $$ begin
  alter publication supabase_realtime add table triage_alerts;
exception when duplicate_object then null; end $$;

do $$ begin
  alter publication supabase_realtime add table intake_sessions;
exception when duplicate_object then null; end $$;

do $$ begin
  alter publication supabase_realtime add table documents;
exception when duplicate_object then null; end $$;
